name: Deploy MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin pymdown-extensions

      - name: Build Pages Script
        run: python scripts/build_pages.py || echo "build_pages.py finished with warning"

      - name: Build MkDocs (with debug)
        run: |
          mkdocs build --verbose
        continue-on-error: true   # حتی اگر خطا داد ادامه بده تا لاگ ببینیم

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy
        uses: actions/deploy-pages@v4